services:
  - type: web
    name: knowyouruniversity
    runtime: python
    buildCommand: bash build.sh
    startCommand: gunicorn --chdir backend_django kyu_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: knowyouruniversity-db
          property: connectionString
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false

databases:
  - name: knowyouruniversity-db
    plan: free
